name: app-deploy

on:
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest

    outputs:
      should_deploy: ${{ steps.filter.outputs.src }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Paths Filter
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - '**.html'
              - '**.ts'
              - '**.js'
              - '**.json'
              - 'Dockerfile'

  site-build:
    name: Build and Upload
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.should_deploy == 'true'

    env:
      CACHE_DIR: dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Creating cache for App build
        uses: actions/cache@v5
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ env.CACHE_DIR }}-key
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build -- --outdir=${{ env.CACHE_DIR }}

  tf-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: site-build
    if: ${{ always() && !failure() && !cancelled() }}

    defaults:
      run:
        working-directory: terraform/

    env:
      ENVIRONMENT: prod
      TF_CLOUD_PROJECT: ByItsCover_PROD
      TF_WORKSPACE: bic-site-prod
      TF_VAR_build_dir: dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Restore cached docker image
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.TF_VAR_build_dir }}
          key: ${{ env.TF_VAR_build_dir }}-key

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Testing Cache
        run: ls ${{ env.TF_VAR_build_dir }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=variables/${{ env.ENVIRONMENT }}.tfvars
